liferay:
  image: tkaefer/liferay-container:latest
  restart: always
  mem_limit: 3G
  memswap_limit: 3G
  links:
    - postgres:postgres
    - mail:mail
  volumes:
    - ./liferay-data:/opt/liferay/data
    - ./portal-ext.properties:/opt/liferay/portal-ext.properties
    - ./setenv.sh:/opt/liferay/tomcat-8.0.32/bin/setenv.sh:ro
postgres:
  image: postgres:9.6
  restart: always
  environment:
    - POSTGRES_USER=liferay
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=lportal
  volumes:
    - ./postgresql-data:/var/lib/postgresql/data
